### PR TITLE
Cleaned up CSS in thargoid-specs.html

### LINKED ISSUE #15: Improve formatting on Thargoid Specs HTML Table
HTML layout is poor and not very clean, needs to be rewritten.

https://www.github.com/antixenoinitiative/axiwiki/tree/main/thargoid-specs.html

### PR DESCRIPTION
**Pull request by hengrv**
Fixes #15 
I have removed all CSS styling from thargoid-specs.html,  and moved them into a CSS file called thargoid-specs.css.

The CSS uses elements to decide the styling, and then the square brackets are for attributes.

There are also some changes to the structure of the html to increase the readability of the code.

### CODE REVIEW

**Comment by hengrv** [comment]
the one issue remaining is data for exerted heart regen speed, I've looked through the axi discord but haven't found anything about it

**Comment by MgramTheDuck** [comment]
I will commit this shortly to see if the CSS file works, if not I might move it into the page-specific override.

**Comment by MgramTheDuck** [comment]
@henrygrv the formatting has pushed, let me know if this appears as expected: https://wiki.antixenoinitiative.com/en/thargoid-specs

It looks great!

**Comment by hengrv** [comment]
the external file worked then? great!

**Pull request merged**
